# Generated by Django 5.1.6 on 2025-07-06 04:53

import django.db.models.deletion
import django_comma_integer_field.fields
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shareholder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', django_comma_integer_field.fields.CommaIntegerField(default=0, verbose_name='مبلغ دریافتی')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='درصد سود')),
                ('insurance_rate', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=7, null=True, verbose_name='درصد بیمه')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=7, null=True, verbose_name='درصد مالیات')),
                ('delay_penalty_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='درصد نرخ جریمه تاخیر')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پرداخت')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ سر رسید')),
                ('purchase_item', models.CharField(blank=True, max_length=255, null=True, verbose_name='برای خرید')),
                ('for_target', models.CharField(blank=True, max_length=255, null=True, verbose_name='برای تامین بخشی از')),
                ('power_of_attorney_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره وکالت نامه')),
                ('power_of_attorney_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ وکالت نامه')),
                ('power_of_attorney_file', models.FileField(blank=True, null=True, upload_to='power_of_attorney_file', verbose_name='وکالت نامه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_settled', models.BooleanField(default=False, verbose_name='تسویه شده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'تسهیلات',
                'verbose_name_plural': 'تسهیلات',
            },
        ),
        migrations.CreateModel(
            name='FacilitySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('fa_name', models.CharField(max_length=255, verbose_name='نام')),
                ('value', models.CharField(verbose_name='مقدار')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='نام')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'نوع تسهیلات',
                'verbose_name_plural': 'نوع تسهیلات',
            },
        ),
        migrations.CreateModel(
            name='FacilityRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', django_comma_integer_field.fields.CommaIntegerField(default=0, verbose_name='مبلغ دریافتی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_repayments', to='facility.facility', verbose_name='تسهیلات')),
            ],
            options={
                'verbose_name': 'سر رسید تسهیلات',
                'verbose_name_plural': 'سر رسید تسهیلات',
            },
        ),
        migrations.CreateModel(
            name='FacilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', django_comma_integer_field.fields.CommaIntegerField(default=0, verbose_name='مبلغ')),
                ('repayment_duration', models.IntegerField(default=1, verbose_name='بازپرداخت به ماه')),
                ('request_description', models.TextField(blank=True, null=True, verbose_name='توحیجات طرح')),
                ('response_description', models.TextField(blank=True, null=True, verbose_name='توضیحات هیات مدیره')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('response_file', models.FileField(blank=True, null=True, upload_to='فایل نتیجه', verbose_name='فایل نتیجه')),
                ('response_date', django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ پاسخ هیات مدیره')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ در خواست')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareholder.shareholder', verbose_name='سهامدار')),
                ('facility_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facilitytype', verbose_name='نوع تسهیلات')),
            ],
            options={
                'verbose_name': 'درخواست تسهیلات',
                'verbose_name_plural': 'درخواست تسهیلات',
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facility.facilityrequest', verbose_name='درخواست تسهیلات'),
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام ضامن')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام پدر')),
                ('id_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره شناسنامه')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='محل صدور')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='facility.facility', verbose_name='تسهیلات')),
            ],
            options={
                'verbose_name': 'ضامن',
                'verbose_name_plural': 'ضامنین',
            },
        ),
    ]
