# Generated by Django 5.1.6 on 2025-02-20 10:59

import django.db.models.deletion
import django_jalali.db.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shareholder", "0002_remove_shareholder_member_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilitySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                ("fa_name", models.CharField(max_length=255, verbose_name="نام فارسی")),
                ("value", models.CharField(verbose_name="مقدار")),
            ],
        ),
        migrations.CreateModel(
            name="FacilityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("fa_name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        verbose_name="درصد سهام به تسهیلات",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="درصد سود"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_shares", models.BigIntegerField(verbose_name="میزان سهام")),
                ("amount", models.BigIntegerField(verbose_name="مبلغ")),
                (
                    "amount_received",
                    models.BigIntegerField(verbose_name="مبلغ دریافتی"),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.0,
                        max_digits=3,
                        verbose_name="درصد سود",
                    ),
                ),
                (
                    "insurance_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.001,
                        max_digits=4,
                        verbose_name="درصد بیمه",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=10,
                        max_digits=4,
                        verbose_name="درصد مالیات",
                    ),
                ),
                (
                    "start_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ شروع"),
                ),
                (
                    "end_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ پایان"),
                ),
                (
                    "description",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "updated_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="تاریخ ویرایش"
                    ),
                ),
                (
                    "shareholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shareholder.shareholder",
                        verbose_name="سهامدار",
                    ),
                ),
                (
                    "facility_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.facilitytype",
                        verbose_name="نوع تسهیلات",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacilityRepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField(verbose_name="مبلغ دریافتی")),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "updated_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="تاریخ ویرایش"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_repayments",
                        to="facility.facility",
                        verbose_name="تسهیلات",
                    ),
                ),
            ],
        ),
    ]
