# Generated by Django 5.1.6 on 2025-03-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitytype',
            name='delay_penalty_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نرخ جریمه تاخیر'),
        ),
        migrations.AlterField(
            model_name='facilitytype',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد سهام به تسهیلات'),
        ),
    ]
