# Generated by Django 5.1.6 on 2025-02-20 11:43

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={"verbose_name": "تسهیلات", "verbose_name_plural": "تسهیلات"},
        ),
        migrations.AlterModelOptions(
            name="facilityrepayment",
            options={
                "verbose_name": "بازپرداخت تسهیلات",
                "verbose_name_plural": "بازپرداخت تسهیلات",
            },
        ),
        migrations.AddField(
            model_name="facilitysetting",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاریخ ثبت",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facilitysetting",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ ویرایش"
            ),
        ),
        migrations.AddField(
            model_name="facilitytype",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاریخ ثبت",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facilitytype",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ ویرایش"
            ),
        ),
    ]
