# Generated by Django 5.1.6 on 2025-02-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0002_alter_facility_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facilitysetting",
            options={"verbose_name": "تنظیمات", "verbose_name_plural": "تنظیمات"},
        ),
        migrations.AlterModelOptions(
            name="facilitytype",
            options={
                "verbose_name": "نوع تسهیلات",
                "verbose_name_plural": "نوع تسهیلات",
            },
        ),
        migrations.AlterField(
            model_name="facility",
            name="amount",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="مبلغ"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="insurance_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=7,
                null=True,
                verbose_name="درصد بیمه",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="interest_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="درصد سود",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="tax_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=7,
                null=True,
                verbose_name="درصد مالیات",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="total_shares",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="میزان سهام"
            ),
        ),
    ]
