# Generated by Django 5.1.6 on 2025-02-23 17:42

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0003_alter_facilitysetting_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="end_date",
            field=django_jalali.db.models.jDateField(verbose_name="تاریخ سر رسید"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="start_date",
            field=django_jalali.db.models.jDateField(verbose_name="تاریخ پرداخت"),
        ),
        migrations.AlterField(
            model_name="facilitysetting",
            name="fa_name",
            field=models.CharField(max_length=255, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="facilitysetting",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="facilitytype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
