# Generated by Django 5.1.6 on 2025-02-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0004_alter_facility_end_date_alter_facility_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="is_overdue",
            field=models.BooleanField(default=False, verbose_name="بدهی"),
        ),
    ]
