# Generated by Django 5.1.6 on 2025-03-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0005_facility_is_overdue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guarantor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام ضامن")),
                (
                    "father_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="نام پدر"
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شماره شناسنامه",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(max_length=10, unique=True, verbose_name="کد ملی"),
                ),
                (
                    "issued_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="محل صدور"
                    ),
                ),
                ("address", models.TextField(verbose_name="آدرس")),
                ("phone", models.CharField(max_length=11, verbose_name="شماره تلفن")),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guarantors",
                        to="facility.facility",
                        verbose_name="تسهیلات",
                    ),
                ),
            ],
            options={
                "verbose_name": "ضامن",
                "verbose_name_plural": "ضامنین",
            },
        ),
        migrations.CreateModel(
            name="PromissoryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="شماره سفته"
                    ),
                ),
                ("amount", models.BigIntegerField(verbose_name="مبلغ سفته")),
                (
                    "issued_by",
                    models.CharField(max_length=255, verbose_name="صادر کننده"),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promissory_notes",
                        to="facility.facility",
                        verbose_name="تسهیلات",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفته",
                "verbose_name_plural": "سفته\u200cها",
            },
        ),
    ]
