# Generated by Django 5.1.6 on 2025-03-02 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0006_guarantor_promissorynote"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[("check", "چک"), ("promissory_note", "سفته")],
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=50, unique=True, verbose_name="شماره"),
                ),
                ("amount", models.BigIntegerField(verbose_name="مبلغ")),
                (
                    "issued_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="صادر کننده"
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شماره حساب"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="نام بانک"
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="نام شعبه"
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="کد بانک"
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="نام صاحب چک",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_instruments",
                        to="facility.facility",
                        verbose_name="تسهیلات",
                    ),
                ),
            ],
            options={
                "verbose_name": "اسناد مالی",
                "verbose_name_plural": "اسناد مالی",
            },
        ),
        migrations.DeleteModel(
            name="PromissoryNote",
        ),
    ]
