# Generated by Django 5.1.6 on 2025-07-06 04:53

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_code', models.CharField(max_length=32, unique=True, verbose_name='کد حسابداری')),
                ('melli_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('father_name', models.CharField(max_length=255, verbose_name='نام پدر')),
                ('birth_date', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('id_number', models.CharField(max_length=20, verbose_name='شماره شناسنامه')),
                ('issued_by', models.CharField(max_length=32, verbose_name='صادره از')),
                ('job', models.CharField(max_length=32, verbose_name='شفل')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('city', models.CharField(max_length=255, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'سهامدار',
                'verbose_name_plural': 'سهامداران',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_number', models.IntegerField(default=0, verbose_name='تعداد سهام')),
                ('amount', models.IntegerField(verbose_name='مبلغ سهام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='زمینه فعالیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareholder.shareholder', verbose_name='سهامدار')),
            ],
            options={
                'verbose_name': 'سهام',
                'verbose_name_plural': 'سهام ها',
            },
        ),
    ]
