# Generated by Django 5.1.6 on 2025-02-10 09:30

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shareholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="کد عضویت"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                ("phone", models.CharField(max_length=11, verbose_name="شماره تلفن")),
                ("address", models.TextField(verbose_name="آدرس")),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "updated_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="تاریخ ویرایش"
                    ),
                ),
            ],
            options={
                "verbose_name": "سهامدار",
                "verbose_name_plural": "سهامداران",
            },
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="مقدار سهام")),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "updated_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="تاریخ ویرایش"
                    ),
                ),
                (
                    "shareholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shareholder.shareholder",
                        verbose_name="سهامدار",
                    ),
                ),
            ],
            options={
                "verbose_name": "سهام",
                "verbose_name_plural": "سهام ها",
            },
        ),
    ]
