# Generated by Django 5.1.6 on 2025-02-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shareholder", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shareholder",
            name="member_id",
        ),
        migrations.AddField(
            model_name="shareholder",
            name="accounting_code",
            field=models.CharField(
                default=1, max_length=32, unique=True, verbose_name="کد حسابداری"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shareholder",
            name="melli_code",
            field=models.CharField(
                default=1, max_length=10, unique=True, verbose_name="کد ملی"
            ),
            preserve_default=False,
        ),
    ]
