# Generated by Django 5.1.6 on 2025-07-06 04:59

import django_comma_integer_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='amount',
            field=django_comma_integer_field.fields.CommaIntegerField(verbose_name='مبلغ سهام'),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_number',
            field=django_comma_integer_field.fields.CommaIntegerField(default=0, verbose_name='تعداد سهام'),
        ),
    ]
