# Generated by Django 5.1.6 on 2025-03-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shareholder", "0002_remove_shareholder_member_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareholder",
            name="father_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="نام پدر"
            ),
        ),
        migrations.AddField(
            model_name="shareholder",
            name="id_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="شماره شناسنامه"
            ),
        ),
    ]
