# Generated by Django 5.1.6 on 2025-07-06 04:53

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='شماره')),
                ('amount', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام بانک')),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شعبه')),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد بانک')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام صاحب چک')),
                ('file', models.FileField(upload_to='promissory_notes', verbose_name='سفته')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_check', to='facility.facility', verbose_name='تسهیلات')),
            ],
            options={
                'verbose_name': 'چک',
                'verbose_name_plural': 'چک ها',
            },
        ),
        migrations.CreateModel(
            name='PowerOfAttorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='شماره وکالت نامه')),
                ('date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ وکالت نامه')),
                ('file', models.FileField(upload_to='power_of_attorney', verbose_name='فایل وکالت نامه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_power_of_attorney', to='facility.guarantor')),
            ],
            options={
                'verbose_name': 'وکالت نامه',
                'verbose_name_plural': 'وکالت نامه ها',
            },
        ),
        migrations.CreateModel(
            name='PromissoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='شماره')),
                ('amount', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام صاحب سفته')),
                ('file', models.FileField(upload_to='promissory_notes', verbose_name='سفته')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_promissory_note', to='facility.facility', verbose_name='تسهیلات')),
            ],
            options={
                'verbose_name': 'سفته',
                'verbose_name_plural': 'سفته ها',
            },
        ),
    ]
