# Generated by Django 5.1.6 on 2025-07-06 04:59

import django_comma_integer_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarantees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='amount',
            field=django_comma_integer_field.fields.CommaIntegerField(default=0, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='promissorynote',
            name='amount',
            field=django_comma_integer_field.fields.CommaIntegerField(default=0, verbose_name='مبلغ'),
        ),
    ]
